/* Experimental local icon matching. Similarity is not a probability; all saves require review. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FPSWarehouse=api})(typeof window==='object'?window:this,function(){
'use strict';
function descriptor(pixels,w,h){
 if(!w||!h||pixels.length!==w*h*4)throw Error('图像尺寸无效');
 var transparent=false;for(var k=3;k<pixels.length;k+=4)if(pixels[k]<100){transparent=true;break}
 var bg=[0,0,0];[0,w-1,(h-1)*w,h*w-1].forEach(function(i){for(var c=0;c<3;c++)bg[c]+=pixels[i*4+c]/4});
 if(!transparent){var bins={},best=null;for(var k=0;k<pixels.length;k+=4){var key=(pixels[k]>>4)+","+(pixels[k+1]>>4)+","+(pixels[k+2]>>4),v=bins[key]||(bins[key]=[0,0,0,0]);v[0]++;for(var c=0;c<3;c++)v[c+1]+=pixels[k+c];if(!best||v[0]>best[0])best=v}if(best)bg=best.slice(1).map(function(v){return v/best[0]})}
 var minX=w,minY=h,maxX=-1,maxY=-1,count=0,mask=new Uint8Array(w*h);
 for(var y=0;y<h;y++)for(var x=0;x<w;x++){var i=y*w+x,p=i*4,d=Math.max(Math.abs(pixels[p]-bg[0]),Math.abs(pixels[p+1]-bg[1]),Math.abs(pixels[p+2]-bg[2]));if(pixels[p+3]>100&&(transparent||d>38)){mask[i]=1;count++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}
 var visited=new Uint8Array(w*h),largest=[];for(var seed=0;seed<mask.length;seed++){if(!mask[seed]||visited[seed])continue;var component=[],stack=[seed];visited[seed]=1;while(stack.length){var at=stack.pop();component.push(at);var ax=at%w,ay=Math.floor(at/w);for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){var nx=ax+dx,ny=ay+dy,ni=ny*w+nx;if(nx>=0&&nx<w&&ny>=0&&ny<h&&mask[ni]&&!visited[ni]){visited[ni]=1;stack.push(ni)}}}if(component.length>largest.length)largest=component}
 if(largest.length<12)return null;minX=w;minY=h;maxX=-1;maxY=-1;largest.forEach(function(i){var x=i%w,y=Math.floor(i/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)});
 if(maxX-minX<3||maxY-minY<3)return null;
 var out=[],gray=[];for(y=0;y<16;y++)for(x=0;x<16;x++){var sx=Math.min(maxX,Math.round(minX+(maxX-minX)*(x+.5)/16)),sy=Math.min(maxY,Math.round(minY+(maxY-minY)*(y+.5)/16)),idx=sy*w+sx,p=idx*4;gray.push(mask[idx]?(pixels[p]+pixels[p+1]+pixels[p+2])/3:0)}
 for(y=0;y<8;y++)for(x=0;x<8;x++){var sx=Math.min(maxX,Math.round(minX+(maxX-minX)*(x+.5)/8)),sy=Math.min(maxY,Math.round(minY+(maxY-minY)*(y+.5)/8)),idx=sy*w+sx,p=idx*4;for(var c=0;c<3;c++)out.push(mask[idx]?pixels[p+c]:0)}
 for(y=0;y<16;y++)for(x=0;x<16;x++){var i=y*16+x;out.push(Math.min(255,Math.abs(gray[i]-gray[y*16+Math.max(0,x-1)])+Math.abs(gray[i]-gray[Math.max(0,y-1)*16+x])))}
 return out;
}
function cosine(a,b,start,end){var dot=0,aa=0,bb=0;for(var i=start;i<end;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/Math.sqrt(aa*bb):0}
function rank(feature,templates,limit){if(!feature)return [];return templates.map(function(t){return {item_id:t.item_id,score:.85*cosine(feature,t.feature,0,192)+.15*cosine(feature,t.feature,192,448)}}).sort(function(a,b){return b.score-a.score}).filter(function(r,i,all){return all.findIndex(function(x){return x.item_id===r.item_id})===i}).slice(0,limit||3)}
function grid(rect,cols,rows){if(!rect||![rect.x,rect.y,rect.w,rect.h].every(Number.isFinite)||rect.x<0||rect.y<0||rect.w<=0||rect.h<=0||!Number.isInteger(cols)||!Number.isInteger(rows)||cols<1||rows<1||cols*rows>128)throw Error('网格需为正整数，最多 128 格');var boxes=[];for(var y=0;y<rows;y++)for(var x=0;x<cols;x++)boxes.push({x:rect.x+x*rect.w/cols,y:rect.y+y*rect.h/rows,w:rect.w/cols,h:rect.h/rows});return boxes}
function plan(catalog,review,records,hash,makeID,stamp){
 var selected=review.filter(function(r){return r.checked});for(var a=0;a<selected.length;a++)for(var b=a+1;b<selected.length;b++){var x=selected[a].box,y=selected[b].box;if(x&&y){var overlap=Math.max(0,Math.min(x.x+x.w,y.x+y.w)-Math.max(x.x,y.x))*Math.max(0,Math.min(x.y+x.h,y.y+y.h)-Math.max(x.y,y.y));if(overlap>Math.min(x.w*x.h,y.w*y.h)*.2)throw Error('勾选区域重叠，请取消重复格子后保存')}}
 var items=new Map(catalog.items.map(function(i){return [i.item_id,i]})),counts=new Map();
 review.filter(function(r){return r.checked}).forEach(function(r){if(!items.has(r.item_id)||!Number.isSafeInteger(r.quantity)||r.quantity<1||r.quantity>1000000000)throw Error('请核对物品和正整数数量');counts.set(r.item_id,(counts.get(r.item_id)||0)+r.quantity)});
 if(!counts.size)throw Error('请勾选已核对的物品');
 var added=[],updated=[],skipped=[];counts.forEach(function(q,id){if(q>1000000000)throw Error('合计数量过大');var item=items.get(id),r=records.find(function(r){return r.kind==='collection'&&/^(三角洲行动|三角洲|delta force)$/i.test(r.game)&&(r.catalog_item_id===id||r.name===item.name)});
 if(r&&(r.import_hash===hash||r.acquisitions.length||Number(r.starting_quantity)>0)){skipped.push(item.name);return}
 var next=Object.assign({},r||{id:makeID(),kind:'collection',game:catalog.game,target:1,acquisitions:[],note:''},{name:item.name,category:item.category,image:item.image,catalog_item_id:id,catalog_object_id:item.object_id,starting_quantity:q,snapshot_date:stamp.slice(0,10),import_source:'warehouse',import_hash:hash,imported_at:stamp,updated_at:stamp,local_dirty:true});if(r)updated.push(next);else added.push(next);
 });return {added:added,updated:updated,skipped:skipped};
}
function mount(options){
 var $=function(id){return document.getElementById(id)},image=null,url='',hash='',epoch=0,busy=false,rect=null,review=[],catalog=null,templates=null,start=null;
 var canvas=$('warehouseCanvas'),ctx=canvas.getContext('2d');function status(t){$('warehouseStatus').textContent=t}function draw(){if(!image)return;canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;ctx.drawImage(image,0,0);if(rect){ctx.strokeStyle='#60d49b';ctx.lineWidth=Math.max(2,canvas.width/400);ctx.strokeRect(rect.x,rect.y,rect.w,rect.h)}}
 function clear(){epoch++;image=null;rect=null;review=[];hash='';busy=false;if(url)URL.revokeObjectURL(url);url='';$('warehouseFile').value='';canvas.hidden=true;$('warehouseReview').innerHTML='';$('warehouseSave').disabled=true;$('warehouseScan').disabled=false;$('warehouseSingle').disabled=false;status('选择仓库截图，拖动框选仓库区域。')}
 function point(e){var b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))}}
 canvas.addEventListener('pointerdown',function(e){if(busy||!image)return;start=point(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',function(e){if(!start)return;var p=point(e);rect={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.abs(start.x-p.x),h:Math.abs(start.y-p.y)};start=null;draw();status('已框选 '+Math.round(rect.w)+' × '+Math.round(rect.h)+' 像素。可按网格扫描，或作为一件多格物品识别。')});
 $('warehouseFile').addEventListener('change',async function(){var f=this.files[0];if(!f)return;clear();var ticket=epoch;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>20*1024*1024){status('请选择不超过 20 MB 的 PNG、JPEG 或 WebP');return}try{var bytes=await f.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes);if(ticket!==epoch)return;hash=Array.from(new Uint8Array(digest)).map(function(x){return x.toString(16).padStart(2,'0')}).join('');url=URL.createObjectURL(f);var im=new Image();im.src=url;await im.decode();if(ticket!==epoch)return;if(im.naturalWidth*im.naturalHeight>20000000)throw Error('尺寸过大，请先裁剪');image=im;rect={x:0,y:0,w:im.naturalWidth,h:im.naturalHeight};canvas.hidden=false;draw();status('请拖动框选仓库区域，避开角色和装备栏。')}catch(e){if(ticket===epoch)status('图片无法读取：'+e.message)}});
 async function load(){if(templates)return;var result=await Promise.all([fetch('./collection-catalog.json',{cache:'no-cache'}),fetch('./warehouse-templates.json',{cache:'no-cache'})]);if(result.some(function(r){return !r.ok}))throw Error('目录或模板下载失败');catalog=await result[0].json();var data=await result[1].json();templates=data.items.map(function(t){return {item_id:t.item_id,feature:Array.from(atob(t.feature),function(c){return c.charCodeAt(0)})}});$('warehouseNames').innerHTML=catalog.items.map(function(i){return '<option value="'+escape(i.name)+'"></option>'}).join('')}
 function escape(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
 function render(){var names=new Map(catalog.items.map(function(i){return [i.item_id,i]}));$('warehouseReview').innerHTML=review.map(function(r,i){return '<div class="card"><img src="'+r.preview+'" alt="格子 '+(i+1)+'" width="96"><label><input type="checkbox" data-wh-check="'+i+'" '+(r.checked?'checked':'')+'> 已核对，导入此格</label><div class="field"><label>物品名称</label><input data-wh-name="'+i+'" list="warehouseNames" value="'+escape(r.name)+'" placeholder="输入名称或选择候选"></div><div class="field"><label>数量（需核对，默认 1）</label><input data-wh-qty="'+i+'" type="number" min="1" value="'+r.quantity+'"></div><div class="actions">'+r.candidates.map(function(c){var item=names.get(c.item_id);return item?'<button class="btn" type="button" data-wh-pick="'+i+'" data-wh-item="'+escape(c.item_id)+'">'+escape(item.name)+' · 相似度 '+c.score.toFixed(2)+'</button>':''}).join('')+'</div></div>'}).join('');
 document.querySelectorAll('[data-wh-check]').forEach(function(e){e.onchange=function(){review[+e.dataset.whCheck].checked=e.checked}});document.querySelectorAll('[data-wh-name]').forEach(function(e){e.oninput=function(){var r=review[+e.dataset.whName],item=catalog.items.find(function(i){return i.name===e.value.trim()});r.name=e.value;r.item_id=item?item.item_id:''}});document.querySelectorAll('[data-wh-qty]').forEach(function(e){e.oninput=function(){review[+e.dataset.whQty].quantity=Number(e.value)}});document.querySelectorAll('[data-wh-pick]').forEach(function(e){e.onclick=function(){var r=review[+e.dataset.whPick],item=names.get(e.dataset.whItem);r.item_id=item.item_id;r.name=item.name;render()}});$('warehouseSave').disabled=!review.length}
 async function scan(single){if(busy)return;if(!image||!rect||rect.w<8||rect.h<8){status('请先框选有效区域');return}var ticket=epoch;busy=true;$('warehouseScan').disabled=true;$('warehouseSingle').disabled=true;$('warehouseSave').disabled=true;status('正在加载图标模板并匹配，本机处理…');try{await load();if(ticket!==epoch)return;var boxes=single?[rect]:grid(rect,Number($('warehouseCols').value),Number($('warehouseRows').value));if(!single)review=[];if(review.length+boxes.length>128)throw Error('候选最多 128 件，请分批处理');for(var i=0;i<boxes.length;i++){if(ticket!==epoch)return;var b=boxes[i],crop=document.createElement('canvas');crop.width=96;crop.height=96;var cc=crop.getContext('2d'),trim=$('warehouseTrim').checked?.17:0;cc.drawImage(image,b.x+1,b.y+b.h*trim,b.w-2,b.h*(1-trim)-2,0,0,96,96);var f=descriptor(cc.getImageData(0,0,96,96).data,96,96);if(!f)continue;var candidates=rank(f,templates,3);review.push({name:'',item_id:'',quantity:1,checked:false,candidates:candidates,preview:crop.toDataURL('image/jpeg',.8),box:b});if(i%8===0)await new Promise(function(r){setTimeout(r,0)})}if(ticket!==epoch)return;render();status('生成 '+review.length+' 个候选，全部默认未勾选。相似度不是准确率；核对物品与数量后再保存。多格物品请清除候选后逐件框选。')}catch(e){if(ticket===epoch)status(e.message)}finally{if(ticket===epoch){busy=false;$('warehouseScan').disabled=false;$('warehouseSingle').disabled=false}}}
 $('warehouseScan').onclick=function(){scan(false)};$('warehouseSingle').onclick=function(){scan(true)};$('warehouseReset').onclick=clear;$('warehouseClearReview').onclick=function(){review=[];$('warehouseReview').innerHTML='';$('warehouseSave').disabled=true};$('warehouseSave').onclick=function(){if(busy||!catalog)return;try{var result=options.onSave(catalog,review,hash);if(result!==false){review=[];render();status(result)}}catch(e){status(e.message)}};clear();return {clear:clear};
}
return {descriptor:descriptor,rank:rank,grid:grid,plan:plan,mount:mount};
});
