/* Experimental local icon matching. Similarity is not a probability; all saves require review. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FPSWarehouse=api})(typeof window==='object'?window:this,function(){
'use strict';
function descriptor(pixels,w,h){
 if(!w||!h||pixels.length!==w*h*4)throw Error('图像尺寸无效');
 var transparent=false;for(var k=3;k<pixels.length;k+=4)if(pixels[k]<100){transparent=true;break}
 var bg=[0,0,0];[0,w-1,(h-1)*w,h*w-1].forEach(function(i){for(var c=0;c<3;c++)bg[c]+=pixels[i*4+c]/4});
 if(!transparent){var bins={},best=null;for(var k=0;k<pixels.length;k+=4){var key=(pixels[k]>>4)+","+(pixels[k+1]>>4)+","+(pixels[k+2]>>4),v=bins[key]||(bins[key]=[0,0,0,0]);v[0]++;for(var c=0;c<3;c++)v[c+1]+=pixels[k+c];if(!best||v[0]>best[0])best=v}if(best)bg=best.slice(1).map(function(v){return v/best[0]})}
 var minX=w,minY=h,maxX=-1,maxY=-1,count=0,mask=new Uint8Array(w*h);
 for(var y=0;y<h;y++)for(var x=0;x<w;x++){var i=y*w+x,p=i*4,d=Math.max(Math.abs(pixels[p]-bg[0]),Math.abs(pixels[p+1]-bg[1]),Math.abs(pixels[p+2]-bg[2]));if(pixels[p+3]>100&&(transparent||d>38)){mask[i]=1;count++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}
 var visited=new Uint8Array(w*h),largest=[];for(var seed=0;seed<mask.length;seed++){if(!mask[seed]||visited[seed])continue;var component=[],stack=[seed];visited[seed]=1;while(stack.length){var at=stack.pop();component.push(at);var ax=at%w,ay=Math.floor(at/w);for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){var nx=ax+dx,ny=ay+dy,ni=ny*w+nx;if(nx>=0&&nx<w&&ny>=0&&ny<h&&mask[ni]&&!visited[ni]){visited[ni]=1;stack.push(ni)}}}if(component.length>largest.length)largest=component}
 if(largest.length<12)return null;minX=w;minY=h;maxX=-1;maxY=-1;largest.forEach(function(i){var x=i%w,y=Math.floor(i/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)});
 if(maxX-minX<3||maxY-minY<3)return null;
 var out=[],gray=[];for(y=0;y<16;y++)for(x=0;x<16;x++){var sx=Math.min(maxX,Math.round(minX+(maxX-minX)*(x+.5)/16)),sy=Math.min(maxY,Math.round(minY+(maxY-minY)*(y+.5)/16)),idx=sy*w+sx,p=idx*4;gray.push(mask[idx]?(pixels[p]+pixels[p+1]+pixels[p+2])/3:0)}
 for(y=0;y<8;y++)for(x=0;x<8;x++){var sx=Math.min(maxX,Math.round(minX+(maxX-minX)*(x+.5)/8)),sy=Math.min(maxY,Math.round(minY+(maxY-minY)*(y+.5)/8)),idx=sy*w+sx,p=idx*4;for(var c=0;c<3;c++)out.push(mask[idx]?pixels[p+c]:0)}
 for(y=0;y<16;y++)for(x=0;x<16;x++){var i=y*16+x;out.push(Math.min(255,Math.abs(gray[i]-gray[y*16+Math.max(0,x-1)])+Math.abs(gray[i]-gray[Math.max(0,y-1)*16+x])))}
 return out;
}
function cosine(a,b,start,end){var dot=0,aa=0,bb=0;for(var i=start;i<end;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/Math.sqrt(aa*bb):0}
function rank(feature,templates,limit){if(!feature)return [];return templates.map(function(t){return {item_id:t.item_id,score:.85*cosine(feature,t.feature,0,192)+.15*cosine(feature,t.feature,192,448)}}).sort(function(a,b){return b.score-a.score}).filter(function(r,i,all){return all.findIndex(function(x){return x.item_id===r.item_id})===i}).slice(0,limit||3)}
function grid(rect,cols,rows){if(!rect||![rect.x,rect.y,rect.w,rect.h].every(Number.isFinite)||rect.x<0||rect.y<0||rect.w<=0||rect.h<=0||!Number.isInteger(cols)||!Number.isInteger(rows)||cols<1||rows<1||cols*rows>128)throw Error('网格需为正整数，最多 128 格');var boxes=[];for(var y=0;y<rows;y++)for(var x=0;x<cols;x++)boxes.push({x:rect.x+x*rect.w/cols,y:rect.y+y*rect.h/rows,w:rect.w/cols,h:rect.h/rows});return boxes}
function sourceOf(r){return r.source_id||r.source_hash||"single"}
function resolveSelected(review){
 var selected=review.filter(function(r){return r.checked}),byID=new Map(),groups=new Map();
 selected.forEach(function(r){if(r.id){if(byID.has(r.id))throw Error('候选编号重复');byID.set(r.id,r)}var group=groups.get(r.item_id)||[];group.push(r);groups.set(r.item_id,group)});
 groups.forEach(function(group){if(new Set(group.map(sourceOf)).size>1)group.forEach(function(r){if((r.overlap_review==='unique'&&r.duplicate_of)||(r.overlap_review!=='unique'&&!r.duplicate_of))throw Error('同类物品跨图出现，请逐项确认独立物品或选择重复项')})});
 function root(r,path){if(!r.duplicate_of)return r;if(path.has(r))throw Error('重复项不能循环关联');path.add(r);var target=byID.get(r.duplicate_of);if(!target||target===r||sourceOf(target)===sourceOf(r)||target.item_id!==r.item_id||target.quantity!==r.quantity)throw Error('重复项需关联另一张图中已勾选的同类物品，数量须一致');return root(target,path)}
 var roots=new Set();selected.forEach(function(r){roots.add(root(r,new Set()))});
 return {selected:selected,effective:Array.from(roots),duplicates:selected.length-roots.size};
}
function plan(catalog,review,records,hash,makeID,stamp){
 var resolved=resolveSelected(review),selected=resolved.selected;
 var items=new Map(catalog.items.map(function(i){return [i.item_id,i]})),counts=new Map();
 selected.forEach(function(r){if(!items.has(r.item_id)||!Number.isSafeInteger(r.quantity)||r.quantity<1||r.quantity>1000000000)throw Error('请核对物品和正整数数量')});
 for(var a=0;a<selected.length;a++)for(var b=a+1;b<selected.length;b++){var x=selected[a].box,y=selected[b].box;if(sourceOf(selected[a])===sourceOf(selected[b])&&x&&y){var overlap=Math.max(0,Math.min(x.x+x.w,y.x+y.w)-Math.max(x.x,y.x))*Math.max(0,Math.min(x.y+x.h,y.y+y.h)-Math.max(x.y,y.y));if(overlap>Math.min(x.w*x.h,y.w*y.h)*.2)throw Error('同一截图的勾选区域重叠，请取消重复格子后保存')}}
 resolved.effective.forEach(function(r){counts.set(r.item_id,(counts.get(r.item_id)||0)+r.quantity)});
 if(!counts.size)throw Error('请勾选已核对的物品');
 var added=[],updated=[],skipped=[];counts.forEach(function(q,id){if(q>1000000000)throw Error('合计数量过大');var item=items.get(id),r=records.find(function(r){return r.kind==='collection'&&/^(三角洲行动|三角洲|delta force)$/i.test(r.game)&&(r.catalog_item_id===id||r.name===item.name)});
 var hashes=Array.from(new Set(selected.filter(function(row){return row.item_id===id&&row.source_hash}).map(function(row){return row.source_hash}))).sort();
 if(r&&(r.import_hash===hash||hashes.some(function(h){return (r.import_hashes||[]).indexOf(h)>=0})||r.acquisitions.length||(r.inventory_events||[]).length||Number(r.starting_quantity)>0)){skipped.push(item.name);return}
 var next=Object.assign({},r||{id:makeID(),kind:'collection',game:catalog.game,target:1,acquisitions:[],note:''},{name:item.name,category:item.category,image:item.image,catalog_item_id:id,catalog_object_id:item.object_id,starting_quantity:q,snapshot_date:new Date(stamp).toLocaleDateString('sv-SE'),import_source:'warehouse',import_hash:hash,import_hashes:hashes,imported_at:stamp,updated_at:stamp,local_dirty:true});if(r)updated.push(next);else added.push(next);
 });return {added:added,updated:updated,skipped:skipped,duplicates:resolved.duplicates};
}
function mount(options){
 var $=function(id){return document.getElementById(id)},pages=[],active=-1,image=null,epoch=0,busy=false,catalog=null,templates=null,start=null,sequence=0;
 var canvas=$('warehouseCanvas'),ctx=canvas.getContext('2d');
 function status(t){$('warehouseStatus').textContent=t}
 function current(){return pages[active]}
 function allReview(){return pages.reduce(function(rows,p){return rows.concat(p.review)},[])}
 function controls(){['warehouseScan','warehouseSingle','warehousePages','warehouseFile','warehouseClearReview','warehouseRemovePage'].forEach(function(id){$(id).disabled=busy});$('warehouseSave').disabled=busy||!allReview().length}
 function draw(){var p=current();if(!image||!p)return;canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;ctx.drawImage(image,0,0);if(p.rect){ctx.strokeStyle='#60d49b';ctx.lineWidth=Math.max(2,canvas.width/400);ctx.strokeRect(p.rect.x,p.rect.y,p.rect.w,p.rect.h)}}
 function syncSettings(){var p=current();if(!p)return;p.cols=Number($('warehouseCols').value);p.rows=Number($('warehouseRows').value);p.trim=$('warehouseTrim').checked}
 function escape(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
 function pageList(){ $('warehousePages').innerHTML=pages.map(function(p,i){return '<option value="'+i+'">图 '+(i+1)+' · '+escape(p.name)+' · '+p.review.length+' 个候选</option>'}).join('');$('warehousePages').value=String(active);$('warehouseBatchInfo').textContent=pages.length+' 张图片 · '+allReview().length+' 个候选（最多 8 张、512 个候选）'}
 function clear(){epoch++;pages.forEach(function(p){URL.revokeObjectURL(p.url)});pages=[];active=-1;image=null;start=null;busy=false;$('warehouseFile').value='';canvas.hidden=true;$('warehouseReview').innerHTML='';pageList();controls();status('可一次选择多张仓库截图，逐图框选与核对，最后汇总保存。')}
 async function activate(index){var p=pages[index];if(!p||busy)return;syncSettings();active=index;start=null;image=null;canvas.hidden=true;busy=true;controls();var ticket=epoch;try{var im=new Image();im.src=p.url;await im.decode();if(ticket!==epoch)return;image=im;$('warehouseCols').value=p.cols;$('warehouseRows').value=p.rows;$('warehouseTrim').checked=p.trim;canvas.hidden=false;draw();pageList();status('当前图 '+(index+1)+'：'+p.name+'。框选与网格设置各图独立保留。')}catch(e){if(ticket===epoch)status('图片无法读取：'+e.message)}finally{if(ticket===epoch){busy=false;controls()}}}
 function point(e){var b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))}}
 canvas.addEventListener('pointerdown',function(e){if(busy||!image)return;start=point(e);canvas.setPointerCapture(e.pointerId)});
 canvas.addEventListener('pointercancel',function(){start=null});canvas.addEventListener('pointerup',function(e){if(!start||!current())return;var p=point(e);current().rect={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.abs(start.x-p.x),h:Math.abs(start.y-p.y)};start=null;draw();status('区域已框选。可按网格扫描，或作为一件多格物品识别。')});
 $('warehouseFile').addEventListener('change',async function(){var files=Array.from(this.files);this.value='';if(!files.length||busy)return;var ticket=epoch,added=0,skipped=0,errors=[];busy=true;controls();try{for(var i=0;i<files.length;i++){if(ticket!==epoch)return;var f=files[i];if(pages.length>=8){errors.push('最多 8 张图片');break}if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>20*1024*1024){errors.push(f.name+'：类型不支持或超过 20 MB');continue}if(pages.reduce(function(n,p){return n+p.size},0)+f.size>80*1024*1024){errors.push('总大小不能超过 80 MB');break}
 var bytes=await f.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes);if(ticket!==epoch)return;var hash=Array.from(new Uint8Array(digest)).map(function(x){return x.toString(16).padStart(2,'0')}).join('');if(pages.some(function(p){return p.hash===hash})){skipped++;continue}
 var url=URL.createObjectURL(f);try{var im=new Image();im.src=url;await im.decode();if(ticket!==epoch){URL.revokeObjectURL(url);return}if(im.naturalWidth*im.naturalHeight>20000000)throw Error('尺寸超过 2,000 万像素');pages.push({id:'image-'+(++sequence),name:f.name,hash:hash,url:url,size:f.size,rect:{x:0,y:0,w:im.naturalWidth,h:im.naturalHeight},cols:8,rows:8,trim:true,review:[]});added++}catch(e){URL.revokeObjectURL(url);if(ticket===epoch)errors.push(f.name+'：'+e.message)}
 }}catch(e){if(ticket===epoch)errors.push(e.message)}finally{if(ticket===epoch){busy=false;pageList();controls();if(added)await activate(pages.length-added);if(ticket!==epoch)return;status('新增 '+added+' 张，跳过完全相同图片 '+skipped+' 张。'+errors.join('；')+' 请逐图生成候选并核对。')}}});
 async function load(){if(templates)return;var result=await Promise.all([fetch('./collection-catalog.json',{cache:'no-cache'}),fetch('./warehouse-templates.json',{cache:'no-cache'})]);if(result.some(function(r){return !r.ok}))throw Error('目录或模板下载失败');catalog=await result[0].json();var data=await result[1].json();templates=data.items.map(function(t){return {item_id:t.item_id,feature:Array.from(atob(t.feature),function(c){return c.charCodeAt(0)})}});$('warehouseNames').innerHTML=catalog.items.map(function(i){return '<option value="'+escape(i.name)+'"></option>'}).join('')}
 function resetOverlap(){allReview().forEach(function(r){r.overlap_review='';r.duplicate_of=''})}
 function render(){pageList();if(!catalog){controls();return}var names=new Map(catalog.items.map(function(i){return [i.item_id,i]})),review=allReview();
 $('warehouseReview').innerHTML=review.map(function(r,i){var others=review.filter(function(x){return x.id!==r.id&&sourceOf(x)!==sourceOf(r)&&x.item_id&&x.item_id===r.item_id}),repeated=others.length>0;return '<div class="card"><b>候选 '+(i+1)+' · '+escape(r.source_name)+'</b><br><img src="'+r.preview+'" alt="候选 '+(i+1)+'" width="96"><label><input type="checkbox" data-wh-check="'+i+'" '+(r.checked?'checked':'')+'> 已核对，导入此格</label><div class="field"><label>物品名称</label><input data-wh-name="'+i+'" list="warehouseNames" value="'+escape(r.name)+'" placeholder="输入名称或选择候选"></div><div class="field"><label>数量（需核对，默认 1）</label><input data-wh-qty="'+i+'" type="number" min="1" value="'+r.quantity+'"></div>'+ (repeated?'<div class="field"><label>跨图重叠核对</label><select data-wh-overlap="'+i+'"><option value="">请选择：是否同一件物品</option><option value="unique" '+(r.overlap_review==='unique'?'selected':'')+'>独立物品 / 独立堆叠，计入数量</option>'+others.map(function(x){return '<option value="'+escape(x.id)+'" '+(r.duplicate_of===x.id?'selected':'')+'>与候选 '+(review.indexOf(x)+1)+' 重复，仅计一次</option>'}).join('')+'</select></div>':'')+'<div class="actions">'+r.candidates.map(function(c){var item=names.get(c.item_id);return item?'<button class="btn" type="button" data-wh-pick="'+i+'" data-wh-item="'+escape(c.item_id)+'">'+escape(item.name)+' · 相似度 '+c.score.toFixed(2)+'</button>':''}).join('')+'</div></div>'}).join('');
 document.querySelectorAll('[data-wh-check]').forEach(function(e){e.onchange=function(){review[+e.dataset.whCheck].checked=e.checked}});
 document.querySelectorAll('[data-wh-name]').forEach(function(e){e.onchange=function(){var r=review[+e.dataset.whName],item=catalog.items.find(function(i){return i.name===e.value.trim()});r.name=e.value;r.item_id=item?item.item_id:'';resetOverlap();render()}});
 document.querySelectorAll('[data-wh-qty]').forEach(function(e){e.oninput=function(){review[+e.dataset.whQty].quantity=Number(e.value)}});
 document.querySelectorAll('[data-wh-overlap]').forEach(function(e){e.onchange=function(){var r=review[+e.dataset.whOverlap];r.overlap_review=this.value==='unique'?'unique':'';r.duplicate_of=this.value==='unique'?'':this.value}});
 document.querySelectorAll('[data-wh-pick]').forEach(function(e){e.onclick=function(){var r=review[+e.dataset.whPick],item=names.get(e.dataset.whItem);r.item_id=item.item_id;r.name=item.name;resetOverlap();render()}});controls()}
 async function scan(single){var p=current();if(busy)return;if(!image||!p||!p.rect||p.rect.w<8||p.rect.h<8){status('请先框选有效区域');return}syncSettings();var ticket=epoch;busy=true;controls();status('正在本机匹配当前图片…');try{await load();if(ticket!==epoch)return;var boxes=single?[p.rect]:grid(p.rect,p.cols,p.rows),fresh=[];if(boxes.length+(single?allReview().length:allReview().length-p.review.length)>512)throw Error('候选合计最多 512 件，请分批处理');
 for(var i=0;i<boxes.length;i++){if(ticket!==epoch)return;var b=boxes[i],crop=document.createElement('canvas');crop.width=96;crop.height=96;var cc=crop.getContext('2d'),trim=p.trim?.17:0;cc.drawImage(image,b.x+1,b.y+b.h*trim,b.w-2,b.h*(1-trim)-2,0,0,96,96);var f=descriptor(cc.getImageData(0,0,96,96).data,96,96);if(!f)continue;fresh.push({id:'crop-'+(++sequence),source_id:p.id,source_hash:p.hash,source_name:p.name,name:'',item_id:'',quantity:1,checked:false,overlap_review:'',duplicate_of:'',candidates:rank(f,templates,3),preview:crop.toDataURL('image/jpeg',.8),box:b});if(i%8===0)await new Promise(function(r){setTimeout(r,0)})}
 if(ticket!==epoch)return;p.review=single?p.review.concat(fresh):fresh;resetOverlap();render();status('当前图生成 '+fresh.length+' 个候选。所有图片候选均保留；同类物品跨图出现时，需确认独立或重复。')
 }catch(e){if(ticket===epoch)status(e.message)}finally{if(ticket===epoch){busy=false;controls()}}}
 $('warehousePages').onchange=function(){return activate(Number(this.value))};$('warehouseScan').onclick=function(){return scan(false)};$('warehouseSingle').onclick=function(){return scan(true)};$('warehouseReset').onclick=clear;
 $('warehouseClearReview').onclick=function(){var p=current();if(busy||!p)return;p.review=[];resetOverlap();render();status('已清除当前图候选，其他图保留。')};
 $('warehouseRemovePage').onclick=function(){if(busy||active<0)return;syncSettings();var p=pages.splice(active,1)[0];URL.revokeObjectURL(p.url);image=null;canvas.hidden=true;active=-1;resetOverlap();render();if(pages.length)activate(0);else status('图片已移除，可继续添加。')};
 $('warehouseSave').onclick=function(){if(busy||!catalog)return;try{var review=allReview(),hash=pages.map(function(p){return p.hash}).sort().join('|'),result=options.onSave(catalog,review,hash);if(result!==false){pages.forEach(function(p){p.review=[]});render();status(result)}}catch(e){status(e.message)}};clear();return {clear:clear};
}
return {descriptor:descriptor,rank:rank,grid:grid,resolveSelected:resolveSelected,plan:plan,mount:mount};
});
